# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: 'stable'
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"

      - name: Get dependencies
        run: flutter pub get

      - name: Build app
        run: flutter run --release

      - name: Build App Bundle
        run: flutter build appbundle
